### ISSUE TITLE
An small problem, really need your help!

### ISSUE THREAD

**Issue by stayhungry1** [VICO-UoE/URL#4]
Hi Prof. Lee! @WeiHongLee

I really appreciate the wonderful work and really want to have a try. When I train each single model(for example, 'dtd'), there is error in meta_dataset.data.reader.py. There are errors in Line 245 and 246: self.base_path = self.dataset_spec.path self.class_set = self.dataset_spec.get_classes(self.split). Since the 'dtd' is str, I wonder the method for solving this problem. Thanks a lot!

**Comment by WeiHongLee** [comment]
Hi, you can check your python version. This code requires python3.6 or a greater version. Hope this can help!
