### ISSUE TITLE
No model update on 5-way 1-shot

### ISSUE THREAD

**Issue by JimZAI** [VICO-UoE/URL#8]
Hi, 
Wei-Hong, thanks for your nice work, it brings me a lot of inspiration.

I wonder is there no model (adapter) update in the setting of  5-way 1-shot ?  (FROM test_extractor.py). 
Or, how to get the results reported in Table 4?

Thanks!
Jim

**Comment by JimZAI** [comment]
In addition, when i use test_extractor_pa.py for 5-way 1-shot task, with the pre-trained/distilled multi-domain feature extractor, the average acc for URL (or TSA) is about 40% on ImageNet, which is far away from 49.6% (or 48.0% ) reported in Table 8 (Appendix of TSA).

**Comment by JimZAI** [comment]
Thanks for your reply.

Indeed, i tried to re-run the test_extractor.py file, following the Section of 'Other Usage'. 

In fact, my key concern is that why there is no task adaptation process (update A_{beta} for URL, or update A_{\beta} and \alpha for TSA) in the file test_extractor.py. It seems that the training/support set of the target task is not utilized to update the model.  Is my understanding correct? please correct me！Thanks.

**Comment by WeiHongLee** [comment]
test_extractor.py provides the implementation of adapting the model by learning a classifier (like NCC, SVM etc) on top of a frozen feature extractor using the support set for different settings. For testing our proposed URL and TSA, please use test_extractor_pa.py and test_extractor_tsa.py, respectively (Note that the parameters of the feature extractor are fixed as well in URL and TSA).

Thanks!

**Comment by JimZAI** [comment]
So the results in Table 4 were achieved by test_extractor_pa.py and test_extractor_tsa.py? Not test_extractor.py?

**Comment by WeiHongLee** [comment]
Table 4 compares results between different methods and results of URL and TSA can be obtained by test_extractor_pa.py and test_extractor_tsa.py respectively. URL and TSA are different methods. You should be able to obtain results of URL using test_extractor_tsa.py but using test_extractor_pa.py would be simpler.

test_extractor.py is used to obtains results in the first cell of Table 3.

**Comment by JimZAI** [comment]
If so, the Section of 'Other Usage' in README.md seems misleading? 

I will try it again following your valuable suggestions. Thanks.

**Comment by WeiHongLee** [comment]
That section gives an example of specifying an evaluation setting. I will add more details on that section. Thanks!
